### ISSUE TITLE
The problem of testing multiplayer in the game

### ISSUE THREAD

**Issue by TomasGameDev** [Alteruna/au-multiplayer-api-docs#3]
Hi, I'm developing an android game and decided to add a cooperative multiplayer mode. I wanted to test the multiplayer mechanics on two different PCs, but the projects always have different application id. Testing on android takes a lot of time because the compilation takes half an hour. Could you please tell me how to effectively test the multiplayer mechanics for my game? Thank you.

**Comment by SimonAlteruna** [comment]
Hello Tomas, I recommend using Discord or Mail for support.
To have the same ID on a project on several computers, make sure that you copy the license data `Assets\Alteruna\Resources\*` to all projects. It would be best to replace the files while Unity is not running to avoid possible issues.
